# Generated by Django 5.1.2 on 2024-11-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
