# Generated by Django 5.1.2 on 2024-10-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='description',
            new_name='text',
        ),
    ]
