# Generated by Django 5.1.2 on 2024-10-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
