# Generated by Django 5.1.2 on 2024-11-18 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='Submission',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),

    ]
