# Generated by Django 5.1.2 on 2024-11-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
