# Generated by Django 5.1.2 on 2024-10-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_submission_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission_ASK',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.submission')),
            ],
            bases=('news.submission',),
        ),
        migrations.CreateModel(
            name='Submission_URL',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.submission')),
            ],
            bases=('news.submission',),
        ),
    ]
