# Generated by Django 5.1.2 on 2024-11-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_description_submission_text'),
        ('news', '0003_submission_ask_submission_url'),
    ]

    operations = [
    ]
