# Generated by Django 5.1.2 on 2024-11-10 19:11

from django.db import migrations

def add_karma_to_existing_submissions(apps, schema_editor):
    Submission = apps.get_model('news', 'Submission')
    Profile = apps.get_model('users', 'Profile')
    Voted = apps.get_model('news', 'Vote')

    for submission in Submission.objects.all():
        num_votes = Voted.objects.filter(submission=submission).count()
        submission.point = num_votes + 1
        submission.save()

        profile = Profile.objects.get(user=submission.author)
        profile.karma += num_votes + 1
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_submission_point'),  # Replace with the actual previous migration file
        ('users', '0001_initial'),  # Replace with the actual previous migration file
    ]

    operations = [
        migrations.RunPython(add_karma_to_existing_submissions),
    ]
