# Generated by Django 5.1.2 on 2024-11-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_vote_upvotedsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='domain',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
