# Generated by Django 5.1.2 on 2024-11-11 09:40

from django.db import migrations
from news.utils import get_domain


def add_domain_to_existing_submissions(apps, schema_editor):
    Submission = apps.get_model('news', 'Submission')
    for submission in Submission.objects.all():
        if submission.url:
            submission.domain = get_domain(submission.url)
            submission.save()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_submission_domain'),
    ]

    operations = [
        migrations.RunPython(add_domain_to_existing_submissions),
    ]
