swagger: "2.0"
info:
  title: Title
  description: Title
  version: 1.0.0
host: www
schemes:
  - https
paths:
  /submissions/{id}:
    get:
      summary: Get a submission
      description: Get a submission by its ID
      parameters:
        - name: id
          in: path
          description: ID of the submission
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:

