### GET all submissions
GET http://localhost:8000/api/submissions

### GET all comments
GET http://localhost:8000/api/comments

### GET newest submissions
GET http://localhost:8000/api/submissions?sort=newest

### Get threads
GET http://localhost:8000/api/threads
Authorization: Token a9aa8ca1bad68bd682684730496829d9f115fa8a

### Get asks
GET http://localhost:8000/api/asks

### Get submissions by domain
GET http://localhost:8000/api/submissions?from=example.com

### Get user's profile
GET http://localhost:8000/api/users/3/profile

### Get user's submissions
GET http://localhost:8000/api/users/6/submissions

### Get user's comments
GET http://localhost:8000/api/users/6/comments

### Get user's hidden submissions
GET http://localhost:8000/api/users/1/hidden
Authorization: Token a9aa8ca1bad68bd682684730496829d9f115fa8a

### Get user's favorite submissions
GET http://localhost:8000/api/users/4/fav_submissions

### Get user's favorite comments
GET http://localhost:8000/api/users/3/fav_comments

### Get user's upvoted submissions
GET http://localhost:8000/api/users/1/up_submissions
Authorization: Token 0d9f80ab61c69ce2f160bde2e3f81bb8b43d74ab

### Get user's upvoted comments
GET http://localhost:8000/api/users/1/up_comments
Authorization: Token a9aa8ca1bad68bd682684730496829d9f115fa8a #4b5acbd77a85ff8c08268b2e7006b9200ddc2041

{
    "title": "New submission to unvote4",
    "url": "https://www.example.com",
    "text": "This is a new submission"
}


### GET submission details by ID
GET http://localhost:8000/api/submissions/2

### Crear una nueva submission
POST http://localhost:8000/api/submissions
Content-Type: application/json
Authorization: Token a9aa8ca1bad68bd682684730496829d9f115fa8a

{
    "title": "API test 2",
    "url": "http://localhost:8000/swagger/"
}

### Update the title of an existing submission
PUT http://localhost:8000/api/submissions/29/update
Content-Type: application/json
Authorization: Token a9aa8ca1bad68bd682684730496829d9f115fa8a #4b5acbd77a85ff8c08268b2e7006b9200ddc2041

{
  "title": "Updated Submission Title2"
}

### Delete an existing submission
DELETE http://localhost:8000/api/submissions/27
Authorization: Token a9aa8ca1bad68bd682684730496829d9f115fa8a #4b5acbd77a85ff8c08268b2e7006b9200ddc2041

### Vote a submission
POST http://localhost:8000/api/submissions/28/vote
Authorization: Token 4b5acbd77a85ff8c08268b2e7006b9200ddc2041 #a9aa8ca1bad68bd682684730496829d9f115fa8a

### Unvote a submission
DELETE http://localhost:8000/api/submissions/28/vote
Authorization: Token 4b5acbd77a85ff8c08268b2e7006b9200ddc2041 #a9aa8ca1bad68bd682684730496829d9f115fa8a

### Favorite a submission
POST http://localhost:8000/api/submissions/28/favorite
Authorization: Token a9aa8ca1bad68bd682684730496829d9f115fa8a

### Unfavorite a submission
DELETE http://localhost:8000/api/submissions/28/favorite
Authorization: Token a9aa8ca1bad68bd682684730496829d9f115fa8a

### Hide a submission
POST http://localhost:8000/api/submissions/28/hide
Authorization: Token a9aa8ca1bad68bd682684730496829d9f115fa8a

### Unhide a submission
DELETE http://localhost:8000/api/submissions/28/hide
Authorization: Token a9aa8ca1bad68bd682684730496829d9f115fa8a
